services:
  - type: web
    name: ai-maternal-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUGGINGFACE_API_KEY
        sync: false  # Add manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false  # Add your Vercel URL manually
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: ./uploads
      - key: LOAD_DEMO_DATA
        value: false

